export enum UserRole {
    ADMINISTRATOR = "ADMINISTRATOR",
    ATTENDANT = "ATTENDANT",
}

export enum NotarySratus {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
}

export enum NotaryType {
    BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE",
    SIGNATURE_AUTHENTICATION = "SIGNATURE_AUTHENTICATION",
    DOCUMENT_AUTHENTICATION = "DOCUMENT_AUTHENTICATION",
    DEED = "DEED",
    OTHER = "OTHER",
}
