
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Notary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Notary
 * 
 */
export type NotaryModel = runtime.Types.Result.DefaultSelection<Prisma.$NotaryPayload>

export type AggregateNotary = {
  _count: NotaryCountAggregateOutputType | null
  _min: NotaryMinAggregateOutputType | null
  _max: NotaryMaxAggregateOutputType | null
}

export type NotaryMinAggregateOutputType = {
  id: string | null
  applicant: string | null
  cpf: string | null
  description: string | null
  requestDate: Date | null
  remarks: string | null
  notaryStatus: $Enums.NotaryStatus | null
  notaryType: $Enums.NotaryType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NotaryMaxAggregateOutputType = {
  id: string | null
  applicant: string | null
  cpf: string | null
  description: string | null
  requestDate: Date | null
  remarks: string | null
  notaryStatus: $Enums.NotaryStatus | null
  notaryType: $Enums.NotaryType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NotaryCountAggregateOutputType = {
  id: number
  applicant: number
  cpf: number
  description: number
  requestDate: number
  remarks: number
  notaryStatus: number
  notaryType: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NotaryMinAggregateInputType = {
  id?: true
  applicant?: true
  cpf?: true
  description?: true
  requestDate?: true
  remarks?: true
  notaryStatus?: true
  notaryType?: true
  createdAt?: true
  updatedAt?: true
}

export type NotaryMaxAggregateInputType = {
  id?: true
  applicant?: true
  cpf?: true
  description?: true
  requestDate?: true
  remarks?: true
  notaryStatus?: true
  notaryType?: true
  createdAt?: true
  updatedAt?: true
}

export type NotaryCountAggregateInputType = {
  id?: true
  applicant?: true
  cpf?: true
  description?: true
  requestDate?: true
  remarks?: true
  notaryStatus?: true
  notaryType?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NotaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notary to aggregate.
   */
  where?: Prisma.NotaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notaries to fetch.
   */
  orderBy?: Prisma.NotaryOrderByWithRelationInput | Prisma.NotaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Notaries
  **/
  _count?: true | NotaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotaryMaxAggregateInputType
}

export type GetNotaryAggregateType<T extends NotaryAggregateArgs> = {
      [P in keyof T & keyof AggregateNotary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNotary[P]>
    : Prisma.GetScalarType<T[P], AggregateNotary[P]>
}




export type NotaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotaryWhereInput
  orderBy?: Prisma.NotaryOrderByWithAggregationInput | Prisma.NotaryOrderByWithAggregationInput[]
  by: Prisma.NotaryScalarFieldEnum[] | Prisma.NotaryScalarFieldEnum
  having?: Prisma.NotaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotaryCountAggregateInputType | true
  _min?: NotaryMinAggregateInputType
  _max?: NotaryMaxAggregateInputType
}

export type NotaryGroupByOutputType = {
  id: string
  applicant: string
  cpf: string
  description: string
  requestDate: Date
  remarks: string | null
  notaryStatus: $Enums.NotaryStatus
  notaryType: $Enums.NotaryType
  createdAt: Date
  updatedAt: Date
  _count: NotaryCountAggregateOutputType | null
  _min: NotaryMinAggregateOutputType | null
  _max: NotaryMaxAggregateOutputType | null
}

export type GetNotaryGroupByPayload<T extends NotaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotaryGroupByOutputType[P]>
      }
    >
  >



export type NotaryWhereInput = {
  AND?: Prisma.NotaryWhereInput | Prisma.NotaryWhereInput[]
  OR?: Prisma.NotaryWhereInput[]
  NOT?: Prisma.NotaryWhereInput | Prisma.NotaryWhereInput[]
  id?: Prisma.StringFilter<"Notary"> | string
  applicant?: Prisma.StringFilter<"Notary"> | string
  cpf?: Prisma.StringFilter<"Notary"> | string
  description?: Prisma.StringFilter<"Notary"> | string
  requestDate?: Prisma.DateTimeFilter<"Notary"> | Date | string
  remarks?: Prisma.StringNullableFilter<"Notary"> | string | null
  notaryStatus?: Prisma.EnumNotaryStatusFilter<"Notary"> | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeFilter<"Notary"> | $Enums.NotaryType
  createdAt?: Prisma.DateTimeFilter<"Notary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Notary"> | Date | string
}

export type NotaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  applicant?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requestDate?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  notaryStatus?: Prisma.SortOrder
  notaryType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NotaryWhereInput | Prisma.NotaryWhereInput[]
  OR?: Prisma.NotaryWhereInput[]
  NOT?: Prisma.NotaryWhereInput | Prisma.NotaryWhereInput[]
  applicant?: Prisma.StringFilter<"Notary"> | string
  cpf?: Prisma.StringFilter<"Notary"> | string
  description?: Prisma.StringFilter<"Notary"> | string
  requestDate?: Prisma.DateTimeFilter<"Notary"> | Date | string
  remarks?: Prisma.StringNullableFilter<"Notary"> | string | null
  notaryStatus?: Prisma.EnumNotaryStatusFilter<"Notary"> | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeFilter<"Notary"> | $Enums.NotaryType
  createdAt?: Prisma.DateTimeFilter<"Notary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Notary"> | Date | string
}, "id">

export type NotaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  applicant?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requestDate?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  notaryStatus?: Prisma.SortOrder
  notaryType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NotaryCountOrderByAggregateInput
  _max?: Prisma.NotaryMaxOrderByAggregateInput
  _min?: Prisma.NotaryMinOrderByAggregateInput
}

export type NotaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotaryScalarWhereWithAggregatesInput | Prisma.NotaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotaryScalarWhereWithAggregatesInput | Prisma.NotaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Notary"> | string
  applicant?: Prisma.StringWithAggregatesFilter<"Notary"> | string
  cpf?: Prisma.StringWithAggregatesFilter<"Notary"> | string
  description?: Prisma.StringWithAggregatesFilter<"Notary"> | string
  requestDate?: Prisma.DateTimeWithAggregatesFilter<"Notary"> | Date | string
  remarks?: Prisma.StringNullableWithAggregatesFilter<"Notary"> | string | null
  notaryStatus?: Prisma.EnumNotaryStatusWithAggregatesFilter<"Notary"> | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeWithAggregatesFilter<"Notary"> | $Enums.NotaryType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Notary"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Notary"> | Date | string
}

export type NotaryCreateInput = {
  id?: string
  applicant: string
  cpf: string
  description: string
  requestDate: Date | string
  remarks?: string | null
  notaryStatus?: $Enums.NotaryStatus
  notaryType: $Enums.NotaryType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotaryUncheckedCreateInput = {
  id?: string
  applicant: string
  cpf: string
  description: string
  requestDate: Date | string
  remarks?: string | null
  notaryStatus?: $Enums.NotaryStatus
  notaryType: $Enums.NotaryType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicant?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requestDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notaryStatus?: Prisma.EnumNotaryStatusFieldUpdateOperationsInput | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeFieldUpdateOperationsInput | $Enums.NotaryType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicant?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requestDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notaryStatus?: Prisma.EnumNotaryStatusFieldUpdateOperationsInput | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeFieldUpdateOperationsInput | $Enums.NotaryType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotaryCreateManyInput = {
  id?: string
  applicant: string
  cpf: string
  description: string
  requestDate: Date | string
  remarks?: string | null
  notaryStatus?: $Enums.NotaryStatus
  notaryType: $Enums.NotaryType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicant?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requestDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notaryStatus?: Prisma.EnumNotaryStatusFieldUpdateOperationsInput | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeFieldUpdateOperationsInput | $Enums.NotaryType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicant?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requestDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notaryStatus?: Prisma.EnumNotaryStatusFieldUpdateOperationsInput | $Enums.NotaryStatus
  notaryType?: Prisma.EnumNotaryTypeFieldUpdateOperationsInput | $Enums.NotaryType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicant?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requestDate?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  notaryStatus?: Prisma.SortOrder
  notaryType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicant?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requestDate?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  notaryStatus?: Prisma.SortOrder
  notaryType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicant?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requestDate?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  notaryStatus?: Prisma.SortOrder
  notaryType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumNotaryStatusFieldUpdateOperationsInput = {
  set?: $Enums.NotaryStatus
}

export type EnumNotaryTypeFieldUpdateOperationsInput = {
  set?: $Enums.NotaryType
}



export type NotarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicant?: boolean
  cpf?: boolean
  description?: boolean
  requestDate?: boolean
  remarks?: boolean
  notaryStatus?: boolean
  notaryType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["notary"]>

export type NotarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicant?: boolean
  cpf?: boolean
  description?: boolean
  requestDate?: boolean
  remarks?: boolean
  notaryStatus?: boolean
  notaryType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["notary"]>

export type NotarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicant?: boolean
  cpf?: boolean
  description?: boolean
  requestDate?: boolean
  remarks?: boolean
  notaryStatus?: boolean
  notaryType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["notary"]>

export type NotarySelectScalar = {
  id?: boolean
  applicant?: boolean
  cpf?: boolean
  description?: boolean
  requestDate?: boolean
  remarks?: boolean
  notaryStatus?: boolean
  notaryType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NotaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "applicant" | "cpf" | "description" | "requestDate" | "remarks" | "notaryStatus" | "notaryType" | "createdAt" | "updatedAt", ExtArgs["result"]["notary"]>

export type $NotaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Notary"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    applicant: string
    cpf: string
    description: string
    requestDate: Date
    remarks: string | null
    notaryStatus: $Enums.NotaryStatus
    notaryType: $Enums.NotaryType
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["notary"]>
  composites: {}
}

export type NotaryGetPayload<S extends boolean | null | undefined | NotaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotaryPayload, S>

export type NotaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotaryCountAggregateInputType | true
  }

export interface NotaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Notary'], meta: { name: 'Notary' } }
  /**
   * Find zero or one Notary that matches the filter.
   * @param {NotaryFindUniqueArgs} args - Arguments to find a Notary
   * @example
   * // Get one Notary
   * const notary = await prisma.notary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotaryFindUniqueArgs>(args: Prisma.SelectSubset<T, NotaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Notary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotaryFindUniqueOrThrowArgs} args - Arguments to find a Notary
   * @example
   * // Get one Notary
   * const notary = await prisma.notary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Notary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryFindFirstArgs} args - Arguments to find a Notary
   * @example
   * // Get one Notary
   * const notary = await prisma.notary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotaryFindFirstArgs>(args?: Prisma.SelectSubset<T, NotaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Notary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryFindFirstOrThrowArgs} args - Arguments to find a Notary
   * @example
   * // Get one Notary
   * const notary = await prisma.notary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Notaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Notaries
   * const notaries = await prisma.notary.findMany()
   * 
   * // Get first 10 Notaries
   * const notaries = await prisma.notary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notaryWithIdOnly = await prisma.notary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotaryFindManyArgs>(args?: Prisma.SelectSubset<T, NotaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Notary.
   * @param {NotaryCreateArgs} args - Arguments to create a Notary.
   * @example
   * // Create one Notary
   * const Notary = await prisma.notary.create({
   *   data: {
   *     // ... data to create a Notary
   *   }
   * })
   * 
   */
  create<T extends NotaryCreateArgs>(args: Prisma.SelectSubset<T, NotaryCreateArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Notaries.
   * @param {NotaryCreateManyArgs} args - Arguments to create many Notaries.
   * @example
   * // Create many Notaries
   * const notary = await prisma.notary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotaryCreateManyArgs>(args?: Prisma.SelectSubset<T, NotaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Notaries and returns the data saved in the database.
   * @param {NotaryCreateManyAndReturnArgs} args - Arguments to create many Notaries.
   * @example
   * // Create many Notaries
   * const notary = await prisma.notary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Notaries and only return the `id`
   * const notaryWithIdOnly = await prisma.notary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NotaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NotaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Notary.
   * @param {NotaryDeleteArgs} args - Arguments to delete one Notary.
   * @example
   * // Delete one Notary
   * const Notary = await prisma.notary.delete({
   *   where: {
   *     // ... filter to delete one Notary
   *   }
   * })
   * 
   */
  delete<T extends NotaryDeleteArgs>(args: Prisma.SelectSubset<T, NotaryDeleteArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Notary.
   * @param {NotaryUpdateArgs} args - Arguments to update one Notary.
   * @example
   * // Update one Notary
   * const notary = await prisma.notary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotaryUpdateArgs>(args: Prisma.SelectSubset<T, NotaryUpdateArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Notaries.
   * @param {NotaryDeleteManyArgs} args - Arguments to filter Notaries to delete.
   * @example
   * // Delete a few Notaries
   * const { count } = await prisma.notary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Notaries
   * const notary = await prisma.notary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotaryUpdateManyArgs>(args: Prisma.SelectSubset<T, NotaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notaries and returns the data updated in the database.
   * @param {NotaryUpdateManyAndReturnArgs} args - Arguments to update many Notaries.
   * @example
   * // Update many Notaries
   * const notary = await prisma.notary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Notaries and only return the `id`
   * const notaryWithIdOnly = await prisma.notary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NotaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NotaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Notary.
   * @param {NotaryUpsertArgs} args - Arguments to update or create a Notary.
   * @example
   * // Update or create a Notary
   * const notary = await prisma.notary.upsert({
   *   create: {
   *     // ... data to create a Notary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Notary we want to update
   *   }
   * })
   */
  upsert<T extends NotaryUpsertArgs>(args: Prisma.SelectSubset<T, NotaryUpsertArgs<ExtArgs>>): Prisma.Prisma__NotaryClient<runtime.Types.Result.GetResult<Prisma.$NotaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Notaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryCountArgs} args - Arguments to filter Notaries to count.
   * @example
   * // Count the number of Notaries
   * const count = await prisma.notary.count({
   *   where: {
   *     // ... the filter for the Notaries we want to count
   *   }
   * })
  **/
  count<T extends NotaryCountArgs>(
    args?: Prisma.Subset<T, NotaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Notary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotaryAggregateArgs>(args: Prisma.Subset<T, NotaryAggregateArgs>): Prisma.PrismaPromise<GetNotaryAggregateType<T>>

  /**
   * Group by Notary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotaryGroupByArgs['orderBy'] }
      : { orderBy?: NotaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Notary model
 */
readonly fields: NotaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Notary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Notary model
 */
export interface NotaryFieldRefs {
  readonly id: Prisma.FieldRef<"Notary", 'String'>
  readonly applicant: Prisma.FieldRef<"Notary", 'String'>
  readonly cpf: Prisma.FieldRef<"Notary", 'String'>
  readonly description: Prisma.FieldRef<"Notary", 'String'>
  readonly requestDate: Prisma.FieldRef<"Notary", 'DateTime'>
  readonly remarks: Prisma.FieldRef<"Notary", 'String'>
  readonly notaryStatus: Prisma.FieldRef<"Notary", 'NotaryStatus'>
  readonly notaryType: Prisma.FieldRef<"Notary", 'NotaryType'>
  readonly createdAt: Prisma.FieldRef<"Notary", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Notary", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Notary findUnique
 */
export type NotaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * Filter, which Notary to fetch.
   */
  where: Prisma.NotaryWhereUniqueInput
}

/**
 * Notary findUniqueOrThrow
 */
export type NotaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * Filter, which Notary to fetch.
   */
  where: Prisma.NotaryWhereUniqueInput
}

/**
 * Notary findFirst
 */
export type NotaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * Filter, which Notary to fetch.
   */
  where?: Prisma.NotaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notaries to fetch.
   */
  orderBy?: Prisma.NotaryOrderByWithRelationInput | Prisma.NotaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notaries.
   */
  cursor?: Prisma.NotaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notaries.
   */
  distinct?: Prisma.NotaryScalarFieldEnum | Prisma.NotaryScalarFieldEnum[]
}

/**
 * Notary findFirstOrThrow
 */
export type NotaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * Filter, which Notary to fetch.
   */
  where?: Prisma.NotaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notaries to fetch.
   */
  orderBy?: Prisma.NotaryOrderByWithRelationInput | Prisma.NotaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notaries.
   */
  cursor?: Prisma.NotaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notaries.
   */
  distinct?: Prisma.NotaryScalarFieldEnum | Prisma.NotaryScalarFieldEnum[]
}

/**
 * Notary findMany
 */
export type NotaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * Filter, which Notaries to fetch.
   */
  where?: Prisma.NotaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notaries to fetch.
   */
  orderBy?: Prisma.NotaryOrderByWithRelationInput | Prisma.NotaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Notaries.
   */
  cursor?: Prisma.NotaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notaries.
   */
  distinct?: Prisma.NotaryScalarFieldEnum | Prisma.NotaryScalarFieldEnum[]
}

/**
 * Notary create
 */
export type NotaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * The data needed to create a Notary.
   */
  data: Prisma.XOR<Prisma.NotaryCreateInput, Prisma.NotaryUncheckedCreateInput>
}

/**
 * Notary createMany
 */
export type NotaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Notaries.
   */
  data: Prisma.NotaryCreateManyInput | Prisma.NotaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Notary createManyAndReturn
 */
export type NotaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * The data used to create many Notaries.
   */
  data: Prisma.NotaryCreateManyInput | Prisma.NotaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Notary update
 */
export type NotaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * The data needed to update a Notary.
   */
  data: Prisma.XOR<Prisma.NotaryUpdateInput, Prisma.NotaryUncheckedUpdateInput>
  /**
   * Choose, which Notary to update.
   */
  where: Prisma.NotaryWhereUniqueInput
}

/**
 * Notary updateMany
 */
export type NotaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Notaries.
   */
  data: Prisma.XOR<Prisma.NotaryUpdateManyMutationInput, Prisma.NotaryUncheckedUpdateManyInput>
  /**
   * Filter which Notaries to update
   */
  where?: Prisma.NotaryWhereInput
  /**
   * Limit how many Notaries to update.
   */
  limit?: number
}

/**
 * Notary updateManyAndReturn
 */
export type NotaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * The data used to update Notaries.
   */
  data: Prisma.XOR<Prisma.NotaryUpdateManyMutationInput, Prisma.NotaryUncheckedUpdateManyInput>
  /**
   * Filter which Notaries to update
   */
  where?: Prisma.NotaryWhereInput
  /**
   * Limit how many Notaries to update.
   */
  limit?: number
}

/**
 * Notary upsert
 */
export type NotaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * The filter to search for the Notary to update in case it exists.
   */
  where: Prisma.NotaryWhereUniqueInput
  /**
   * In case the Notary found by the `where` argument doesn't exist, create a new Notary with this data.
   */
  create: Prisma.XOR<Prisma.NotaryCreateInput, Prisma.NotaryUncheckedCreateInput>
  /**
   * In case the Notary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotaryUpdateInput, Prisma.NotaryUncheckedUpdateInput>
}

/**
 * Notary delete
 */
export type NotaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
  /**
   * Filter which Notary to delete.
   */
  where: Prisma.NotaryWhereUniqueInput
}

/**
 * Notary deleteMany
 */
export type NotaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notaries to delete
   */
  where?: Prisma.NotaryWhereInput
  /**
   * Limit how many Notaries to delete.
   */
  limit?: number
}

/**
 * Notary without action
 */
export type NotaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notary
   */
  select?: Prisma.NotarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notary
   */
  omit?: Prisma.NotaryOmit<ExtArgs> | null
}
