
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  ATTENDANT: 'ATTENDANT'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const NotaryStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
} as const

export type NotaryStatus = (typeof NotaryStatus)[keyof typeof NotaryStatus]


export const NotaryType = {
  BIRTH_CERTIFICATE: 'BIRTH_CERTIFICATE',
  SIGNATURE_AUTHENTICATION: 'SIGNATURE_AUTHENTICATION',
  DOCUMENT_AUTHENTICATION: 'DOCUMENT_AUTHENTICATION',
  DEED: 'DEED',
  OTHER: 'OTHER'
} as const

export type NotaryType = (typeof NotaryType)[keyof typeof NotaryType]
